compile:
	/usr/bin/gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp -D_FILE_OFFSET_BITS=64 -I/usr/include/apr-1.0 deepseek-r1-distill-llama-70b.c -o deepseek-r1-distill-llama-70b_run -lapr-1 -lgomp -lm
	/usr/bin/gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp -D_FILE_OFFSET_BITS=64 -I/usr/include/apr-1.0 llama-3.1-8b-instant.c -o llama-3.1-8b-instant_run -lapr-1 -lgomp -lm
	/usr/bin/gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp -D_FILE_OFFSET_BITS=64 -I/usr/include/apr-1.0 meta-llama-4-scout-17b-16e-instruc.c -o meta-llama-4-scout-17b-16e-instruc_run -lapr-1 -lgomp -lm
	/usr/bin/gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp -D_FILE_OFFSET_BITS=64 -I/usr/include/apr-1.0 meta-llama-llama-4-maverick-17b-128e-instruct.c -o meta-llama-llama-4-maverick-17b-128e-instruct_run -lapr-1 -lgomp -lm
	/usr/bin/gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp -D_FILE_OFFSET_BITS=64 -I/usr/include/apr-1.0 the-algorithms.c -o the-algorithms_run -lapr-1 -lgomp -lm
	/usr/bin/gcc -pipe -Wall -O3 -fomit-frame-pointer -march=native -fopenmp -D_FILE_OFFSET_BITS=64 -I/usr/include/apr-1.0 qwen-qwq-32b.c -o qwen-qwq-32b_run -lapr-1 -lgomp -lm
